/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CallTypeRouteImport } from './routes/call.$type'
import { Route as VesselsIndexRouteImport } from './routes/vessels.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CallTypeRoute = CallTypeRouteImport.update({
  id: '/call/$type',
  path: '/call/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselsIndexRoute = VesselsIndexRouteImport.update({
  id: '/vessels/',
  path: '/vessels/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/call/$type': typeof CallTypeRoute
  '/vessels/': typeof VesselsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/call/$type': typeof CallTypeRoute
  '/vessels': typeof VesselsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/call/$type': typeof CallTypeRoute
  '/vessels/': typeof VesselsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/call/$type' | '/vessels/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/call/$type' | '/vessels'
  id: '__root__' | '/' | '/settings' | '/call/$type' | '/vessels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  CallTypeRoute: typeof CallTypeRoute
  VesselsIndexRoute: typeof VesselsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$type': {
      id: '/call/$type'
      path: '/call/$type'
      fullPath: '/call/$type'
      preLoaderRoute: typeof CallTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessels/': {
      id: '/vessels/'
      path: '/vessels'
      fullPath: '/vessels/'
      preLoaderRoute: typeof VesselsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  CallTypeRoute: CallTypeRoute,
  VesselsIndexRoute: VesselsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
