/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as CallTypeRouteImport } from './routes/call.$type'
import { Route as VesselsIndexRouteImport } from './routes/vessels.index'
import { Route as VesselsIdRouteImport } from './routes/vessels.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const CallTypeRoute = CallTypeRouteImport.update({
  id: '/call/$type',
  path: '/call/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselsIndexRoute = VesselsIndexRouteImport.update({
  id: '/vessels/',
  path: '/vessels/',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselsIdRoute = VesselsIdRouteImport.update({
  id: '/vessels/$id',
  path: '/vessels/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/api/tts': typeof ApiTtsRoute
  '/call/$type': typeof CallTypeRoute
  '/vessels/$id': typeof VesselsIdRoute
  '/vessels/': typeof VesselsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/api/tts': typeof ApiTtsRoute
  '/call/$type': typeof CallTypeRoute
  '/vessels/$id': typeof VesselsIdRoute
  '/vessels': typeof VesselsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/api/tts': typeof ApiTtsRoute
  '/call/$type': typeof CallTypeRoute
  '/vessels/$id': typeof VesselsIdRoute
  '/vessels/': typeof VesselsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/privacy'
    | '/settings'
    | '/api/tts'
    | '/call/$type'
    | '/vessels/$id'
    | '/vessels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/privacy'
    | '/settings'
    | '/api/tts'
    | '/call/$type'
    | '/vessels/$id'
    | '/vessels'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/privacy'
    | '/settings'
    | '/api/tts'
    | '/call/$type'
    | '/vessels/$id'
    | '/vessels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  ApiTtsRoute: typeof ApiTtsRoute
  CallTypeRoute: typeof CallTypeRoute
  VesselsIdRoute: typeof VesselsIdRoute
  VesselsIndexRoute: typeof VesselsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$type': {
      id: '/call/$type'
      path: '/call/$type'
      fullPath: '/call/$type'
      preLoaderRoute: typeof CallTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessels/': {
      id: '/vessels/'
      path: '/vessels'
      fullPath: '/vessels/'
      preLoaderRoute: typeof VesselsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessels/$id': {
      id: '/vessels/$id'
      path: '/vessels/$id'
      fullPath: '/vessels/$id'
      preLoaderRoute: typeof VesselsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  ApiTtsRoute: ApiTtsRoute,
  CallTypeRoute: CallTypeRoute,
  VesselsIdRoute: VesselsIdRoute,
  VesselsIndexRoute: VesselsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
